name: Build
on:
  pull_request:
    types: [opened, synchronize, reopened]
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: 7.0.x
      - name: Restore Dependencies
        run: dotnet restore ProjectPyramid.sln
      - name: Build
        run: dotnet build ProjectPyramid.sln --configuration Release --no-restore
      - name: Test
        working-directory: ./ProjectPyramid.API.Test
        run: dotnet test --collect:"XPlat Code Coverage"
      - name: Test
        working-directory: ./ProjectPyramid.Core.Test
        run: dotnet test --collect:"XPlat Code Coverage"        
      - name: CodeCov
        run: |
          curl -Os https://uploader.codecov.io/latest/linux/codecov
          chmod +x codecov
          ./codecov -t ${{ secrets.CODECOV_TOKEN }}
